"""
AI-Powered Analysis Planner
Phase 1: AI analyzes code to create analysis plan
Phase 2: Execute detailed analysis based on plan
"""

import os
from typing import Dict, Any, List
from dataclasses import dataclass


@dataclass
class AnalysisPlan:
    """Analysis plan generated by AI"""
    priority_areas: List[str]  # Which parts to focus on
    analysis_strategies: List[str]  # How to analyze
    expected_issues: List[str]  # What problems to look for
    code_characteristics: Dict[str, Any]  # Code properties AI identified
    recommendations: List[str]  # Initial recommendations


class AnalysisPlanner:
    """AI-powered analysis planner"""

    def __init__(self, ai_provider: str = "openai", model: str = "gpt-4"):
        self.provider = ai_provider
        self.model = model
        self.client = self._initialize_client()

    def _initialize_client(self):
        """Initialize LLM client"""
        if self.provider == 'openai':
            try:
                import openai
                api_key = os.getenv('OPENAI_API_KEY')
                if not api_key:
                    raise ValueError("OPENAI_API_KEY not found in environment")
                openai.api_key = api_key
                return openai
            except ImportError:
                raise ImportError("openai package not installed. Run: pip install openai")

        elif self.provider == 'azure-openai' or self.provider == 'azure_openai':
            try:
                import openai

                # Azure OpenAI requires specific configuration
                endpoint = os.getenv('AZURE_OPENAI_ENDPOINT')
                api_key = os.getenv('AZURE_OPENAI_KEY')
                api_version = os.getenv('AZURE_OPENAI_API_VERSION', '2024-02-15-preview')
                deployment = os.getenv('AZURE_OPENAI_DEPLOYMENT') or self.model

                if not endpoint or not api_key:
                    raise ValueError(
                        "Azure OpenAI configuration incomplete. "
                        "Set AZURE_OPENAI_ENDPOINT and AZURE_OPENAI_KEY environment variables."
                    )

                # Configure for Azure
                openai.api_type = "azure"
                openai.api_base = endpoint
                openai.api_key = api_key
                openai.api_version = api_version

                # Store deployment name for later use
                self.azure_deployment = deployment

                return openai
            except ImportError:
                raise ImportError("openai package not installed. Run: pip install openai")

        elif self.provider == 'anthropic':
            try:
                from anthropic import Anthropic
                api_key = os.getenv('ANTHROPIC_API_KEY')
                if not api_key:
                    raise ValueError("ANTHROPIC_API_KEY not found in environment")
                return Anthropic(api_key=api_key)
            except ImportError:
                raise ImportError("anthropic package not installed. Run: pip install anthropic")

        else:
            raise ValueError(f"Unsupported provider: {self.provider}")

    def create_analysis_plan(self, code: str, file_path: str) -> AnalysisPlan:
        """
        Phase 1: AI creates analysis plan

        AI will:
        1. Understand code purpose and structure
        2. Identify critical areas that need deep analysis
        3. Suggest analysis strategies
        4. Predict potential issues
        """

        prompt = self._create_planning_prompt(code, file_path)
        response = self._call_llm(prompt, max_tokens=2000)

        # Parse AI response into AnalysisPlan
        return self._parse_plan_response(response)

    def _create_planning_prompt(self, code: str, file_path: str) -> str:
        """Create prompt for analysis planning"""
        return f"""You are a senior code analyst. Analyze this Spark/Python code and create a detailed analysis plan.

File: {file_path}
Code length: {len(code.split(chr(10)))} lines

Code:
```python
{code[:5000]}  # First 5000 chars
```

Create an analysis plan by answering:

## 1. Code Characteristics
- What type of code is this? (ETL job, API, library, etc.)
- What technology stack? (Spark version, frameworks)
- Is this auto-generated or hand-written?
- What's the complexity level? (simple/moderate/complex)

## 2. Priority Analysis Areas
List 3-5 specific areas that need deep analysis (be specific about line ranges or components):
- Area 1: [description + why it's critical]
- Area 2: [description + why it's critical]
...

## 3. Analysis Strategies
For each priority area, suggest how to analyze:
- What to check for?
- Which tools/techniques to use?
- What patterns to look for?

## 4. Expected Issues
Based on code patterns you see, predict likely issues:
- Performance issues
- Security vulnerabilities
- Logic errors
- Code quality problems

## 5. Initial Recommendations
Quick wins or critical fixes you can already identify:
- Fix 1: [what + where + why]
- Fix 2: [what + where + why]
...

Format your response clearly with headers. Be specific and actionable.
"""

    def _call_llm(self, prompt: str, max_tokens: int = 2000) -> str:
        """Call LLM to generate plan"""
        try:
            if self.provider == 'openai':
                response = self.client.ChatCompletion.create(
                    model=self.model,
                    messages=[
                        {"role": "system", "content": "You are an expert code analyst creating analysis plans."},
                        {"role": "user", "content": prompt}
                    ],
                    max_tokens=max_tokens,
                    temperature=0.3  # Lower temperature for more focused analysis
                )
                return response.choices[0].message.content

            elif self.provider == 'azure-openai' or self.provider == 'azure_openai':
                # Azure OpenAI uses engine (deployment name) instead of model
                response = self.client.ChatCompletion.create(
                    engine=self.azure_deployment,  # Use deployment name for Azure
                    messages=[
                        {"role": "system", "content": "You are an expert code analyst creating analysis plans."},
                        {"role": "user", "content": prompt}
                    ],
                    max_tokens=max_tokens,
                    temperature=0.3
                )
                return response.choices[0].message.content

            elif self.provider == 'anthropic':
                message = self.client.messages.create(
                    model=self.model,
                    max_tokens=max_tokens,
                    messages=[{"role": "user", "content": prompt}],
                    system="You are an expert code analyst creating analysis plans."
                )
                return message.content[0].text

        except Exception as e:
            return f"Error calling LLM: {str(e)}"

    def _parse_plan_response(self, response: str) -> AnalysisPlan:
        """Parse AI response into structured AnalysisPlan"""

        # Simple parsing - extract sections
        priority_areas = []
        strategies = []
        expected_issues = []
        recommendations = []
        characteristics = {}

        lines = response.split('\n')
        current_section = None

        for line in lines:
            line = line.strip()

            # Detect sections
            if 'priority' in line.lower() and 'area' in line.lower():
                current_section = 'priority'
            elif 'strateg' in line.lower():
                current_section = 'strategy'
            elif 'expected' in line.lower() and 'issue' in line.lower():
                current_section = 'issues'
            elif 'recommendation' in line.lower():
                current_section = 'recommendations'
            elif 'characteristic' in line.lower():
                current_section = 'characteristics'

            # Extract content
            if line.startswith('-') or line.startswith('•') or (len(line) > 0 and line[0].isdigit() and '.' in line):
                content = line.lstrip('-•0123456789. ')

                if current_section == 'priority':
                    priority_areas.append(content)
                elif current_section == 'strategy':
                    strategies.append(content)
                elif current_section == 'issues':
                    expected_issues.append(content)
                elif current_section == 'recommendations':
                    recommendations.append(content)

        # If parsing failed, use full response
        if not priority_areas:
            priority_areas = ["Full code review needed - parsing failed"]
            strategies = ["Manual analysis required"]
            expected_issues = [response[:200]]

        return AnalysisPlan(
            priority_areas=priority_areas,
            analysis_strategies=strategies,
            expected_issues=expected_issues,
            code_characteristics=characteristics,
            recommendations=recommendations
        )


if __name__ == "__main__":
    # Test the planner
    test_code = """
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("test").getOrCreate()
df = spark.sql("SELECT * FROM users WHERE id = '{}'".format(user_id))
df.collect()
    """

    planner = AnalysisPlanner(ai_provider="openai")
    plan = planner.create_analysis_plan(test_code, "test.py")

    print("=== Analysis Plan ===")
    print(f"\nPriority Areas: {plan.priority_areas}")
    print(f"\nStrategies: {plan.analysis_strategies}")
    print(f"\nExpected Issues: {plan.expected_issues}")
    print(f"\nRecommendations: {plan.recommendations}")
